apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-headless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-rs-headless
  template:
    metadata:
      labels:
        app: myapp-rs-headless
    spec:
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - containerPort: 8080
