apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-compress
spec:
  containers:
  - image: nginx
    name: nginx-compress
    volumeMounts:
    - name: nginx-compress-config
      mountPath: /etc/nginx/conf.d/
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: nginx-compress-config
    configMap:
      name: nginx-gzip-config
