apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-huge-req
spec:
  containers:
  - name: myapp
    image: ghcr.io/c1t1d0s7/go-myweb:alpine
    resources:
      requests:
        cpu: 4000m
        memory: 4Gi
