apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-rs-ns
  template:
    metadata:
      labels:
        app: myapp-rs-ns
    spec:
      nodeSelector:
        gpu: highend
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
