apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-cordon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-rs-cordon
  template:
    metadata:
      labels:
        app: myapp-rs-cordon
    spec:
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
