apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-namedport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-rs-namedport
  template:
    metadata:
      labels:
        app: myapp-rs-namedport
    spec:
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - name: myapp-http
          containerPort: 8080
